# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\EnterDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnterDataDialog(object):
    def setupUi(self, EnterDataDialog):
        EnterDataDialog.setObjectName("EnterDataDialog")
        EnterDataDialog.resize(506, 408)
        self.gridLayout = QtWidgets.QGridLayout(EnterDataDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_cancel = QtWidgets.QPushButton(EnterDataDialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 14, 2, 1, 1)
        self.line_edit_cheque_no = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_cheque_no.setObjectName("line_edit_cheque_no")
        self.gridLayout.addWidget(self.line_edit_cheque_no, 9, 1, 1, 1)
        self.lbl_chalan_no = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_chalan_no.setObjectName("lbl_chalan_no")
        self.gridLayout.addWidget(self.lbl_chalan_no, 10, 0, 1, 1)
        self.lbl_payment_paid_date = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_payment_paid_date.setObjectName("lbl_payment_paid_date")
        self.gridLayout.addWidget(self.lbl_payment_paid_date, 7, 0, 1, 1)
        self.btn_add_record = QtWidgets.QPushButton(EnterDataDialog)
        self.btn_add_record.setObjectName("btn_add_record")
        self.gridLayout.addWidget(self.btn_add_record, 13, 2, 1, 1)
        self.line_edit_qty = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_qty.setMaximumSize(QtCore.QSize(341, 16777215))
        self.line_edit_qty.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_edit_qty.setObjectName("line_edit_qty")
        self.gridLayout.addWidget(self.line_edit_qty, 4, 1, 1, 1)
        self.line_edit_chalan_no = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_chalan_no.setObjectName("line_edit_chalan_no")
        self.gridLayout.addWidget(self.line_edit_chalan_no, 10, 1, 1, 1)
        self.lbl_remarks = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_remarks.setObjectName("lbl_remarks")
        self.gridLayout.addWidget(self.lbl_remarks, 11, 0, 1, 1)
        self.llbl_selling_quantity = QtWidgets.QLabel(EnterDataDialog)
        self.llbl_selling_quantity.setObjectName("llbl_selling_quantity")
        self.gridLayout.addWidget(self.llbl_selling_quantity, 4, 0, 1, 1)
        self.lbl_size = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_size.setObjectName("lbl_size")
        self.gridLayout.addWidget(self.lbl_size, 3, 0, 1, 1)
        self.line_edit_selling_rate = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_selling_rate.setMaxLength(32700)
        self.line_edit_selling_rate.setObjectName("line_edit_selling_rate")
        self.gridLayout.addWidget(self.line_edit_selling_rate, 5, 1, 1, 1)
        self.combo_box_size = QtWidgets.QComboBox(EnterDataDialog)
        self.combo_box_size.setMinimumSize(QtCore.QSize(69, 0))
        self.combo_box_size.setMaximumSize(QtCore.QSize(69, 16777215))
        self.combo_box_size.setObjectName("combo_box_size")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.combo_box_size.addItem("")
        self.gridLayout.addWidget(self.combo_box_size, 3, 1, 1, 1)
        self.lbl_purchase_rate_of_44_size = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_purchase_rate_of_44_size.setObjectName("lbl_purchase_rate_of_44_size")
        self.gridLayout.addWidget(self.lbl_purchase_rate_of_44_size, 6, 0, 1, 1)
        self.lbl_cheque_no = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_cheque_no.setObjectName("lbl_cheque_no")
        self.gridLayout.addWidget(self.lbl_cheque_no, 9, 0, 1, 1)
        self.date_edit_payment_paid_date = QtWidgets.QDateEdit(EnterDataDialog)
        self.date_edit_payment_paid_date.setCalendarPopup(True)
        self.date_edit_payment_paid_date.setObjectName("date_edit_payment_paid_date")
        self.gridLayout.addWidget(self.date_edit_payment_paid_date, 7, 1, 1, 1)
        self.line_edit_purchase_rate_of_44_size = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_purchase_rate_of_44_size.setObjectName("line_edit_purchase_rate_of_44_size")
        self.gridLayout.addWidget(self.line_edit_purchase_rate_of_44_size, 6, 1, 1, 1)
        self.lbl_selling_rate = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_selling_rate.setObjectName("lbl_selling_rate")
        self.gridLayout.addWidget(self.lbl_selling_rate, 5, 0, 1, 1)
        self.lbl_payment_paid_amount = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_payment_paid_amount.setObjectName("lbl_payment_paid_amount")
        self.gridLayout.addWidget(self.lbl_payment_paid_amount, 8, 0, 1, 1)
        self.line_edit_payment_paid_amount = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_payment_paid_amount.setObjectName("line_edit_payment_paid_amount")
        self.gridLayout.addWidget(self.line_edit_payment_paid_amount, 8, 1, 1, 1)
        self.line_edit_party_name = QtWidgets.QLineEdit(EnterDataDialog)
        self.line_edit_party_name.setObjectName("line_edit_party_name")
        self.gridLayout.addWidget(self.line_edit_party_name, 1, 1, 1, 1)
        self.lbl_gsm = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_gsm.setObjectName("lbl_gsm")
        self.gridLayout.addWidget(self.lbl_gsm, 2, 0, 1, 1)
        self.combo_box_gsm = QtWidgets.QComboBox(EnterDataDialog)
        self.combo_box_gsm.setMinimumSize(QtCore.QSize(69, 22))
        self.combo_box_gsm.setMaximumSize(QtCore.QSize(69, 16777215))
        self.combo_box_gsm.setObjectName("combo_box_gsm")
        self.combo_box_gsm.addItem("")
        self.combo_box_gsm.addItem("")
        self.gridLayout.addWidget(self.combo_box_gsm, 2, 1, 1, 1)
        self.lbl_date = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_date.setObjectName("lbl_date")
        self.gridLayout.addWidget(self.lbl_date, 0, 0, 1, 1)
        self.date_edit_date = QtWidgets.QDateEdit(EnterDataDialog)
        self.date_edit_date.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.date_edit_date.setCalendarPopup(True)
        self.date_edit_date.setObjectName("date_edit_date")
        self.gridLayout.addWidget(self.date_edit_date, 0, 1, 1, 1)
        self.lbl_party_name = QtWidgets.QLabel(EnterDataDialog)
        self.lbl_party_name.setObjectName("lbl_party_name")
        self.gridLayout.addWidget(self.lbl_party_name, 1, 0, 1, 1)
        self.text_edit_remarks = QtWidgets.QTextEdit(EnterDataDialog)
        self.text_edit_remarks.setObjectName("text_edit_remarks")
        self.gridLayout.addWidget(self.text_edit_remarks, 11, 1, 1, 1)
        self.lbl_chalan_no.setBuddy(self.line_edit_chalan_no)
        self.lbl_payment_paid_date.setBuddy(self.date_edit_payment_paid_date)
        self.lbl_remarks.setBuddy(self.text_edit_remarks)
        self.llbl_selling_quantity.setBuddy(self.line_edit_qty)
        self.lbl_size.setBuddy(self.combo_box_size)
        self.lbl_purchase_rate_of_44_size.setBuddy(self.line_edit_purchase_rate_of_44_size)
        self.lbl_cheque_no.setBuddy(self.line_edit_cheque_no)
        self.lbl_selling_rate.setBuddy(self.line_edit_selling_rate)
        self.lbl_payment_paid_amount.setBuddy(self.line_edit_payment_paid_amount)
        self.lbl_gsm.setBuddy(self.combo_box_gsm)
        self.lbl_date.setBuddy(self.date_edit_date)
        self.lbl_party_name.setBuddy(self.line_edit_party_name)

        self.retranslateUi(EnterDataDialog)
        QtCore.QMetaObject.connectSlotsByName(EnterDataDialog)
        EnterDataDialog.setTabOrder(self.date_edit_date, self.line_edit_party_name)
        EnterDataDialog.setTabOrder(self.line_edit_party_name, self.combo_box_gsm)
        EnterDataDialog.setTabOrder(self.combo_box_gsm, self.combo_box_size)
        EnterDataDialog.setTabOrder(self.combo_box_size, self.line_edit_qty)
        EnterDataDialog.setTabOrder(self.line_edit_qty, self.line_edit_selling_rate)
        EnterDataDialog.setTabOrder(self.line_edit_selling_rate, self.line_edit_purchase_rate_of_44_size)
        EnterDataDialog.setTabOrder(self.line_edit_purchase_rate_of_44_size, self.date_edit_payment_paid_date)
        EnterDataDialog.setTabOrder(self.date_edit_payment_paid_date, self.line_edit_payment_paid_amount)
        EnterDataDialog.setTabOrder(self.line_edit_payment_paid_amount, self.line_edit_cheque_no)
        EnterDataDialog.setTabOrder(self.line_edit_cheque_no, self.line_edit_chalan_no)
        EnterDataDialog.setTabOrder(self.line_edit_chalan_no, self.text_edit_remarks)
        EnterDataDialog.setTabOrder(self.text_edit_remarks, self.btn_add_record)
        EnterDataDialog.setTabOrder(self.btn_add_record, self.btn_cancel)

    def retranslateUi(self, EnterDataDialog):
        _translate = QtCore.QCoreApplication.translate
        EnterDataDialog.setWindowTitle(_translate("EnterDataDialog", "Enter Data"))
        self.btn_cancel.setText(_translate("EnterDataDialog", "Cancel"))
        self.lbl_chalan_no.setText(_translate("EnterDataDialog", "Chalan No.:"))
        self.lbl_payment_paid_date.setText(_translate("EnterDataDialog", "Payment paid date:"))
        self.btn_add_record.setText(_translate("EnterDataDialog", "Add Record"))
        self.lbl_remarks.setText(_translate("EnterDataDialog", "Remarks:"))
        self.llbl_selling_quantity.setText(_translate("EnterDataDialog", "Quantity:"))
        self.lbl_size.setText(_translate("EnterDataDialog", "Size:"))
        self.combo_box_size.setItemText(0, _translate("EnterDataDialog", "36"))
        self.combo_box_size.setItemText(1, _translate("EnterDataDialog", "44"))
        self.combo_box_size.setItemText(2, _translate("EnterDataDialog", "48"))
        self.combo_box_size.setItemText(3, _translate("EnterDataDialog", "54"))
        self.combo_box_size.setItemText(4, _translate("EnterDataDialog", "58"))
        self.combo_box_size.setItemText(5, _translate("EnterDataDialog", "60"))
        self.combo_box_size.setItemText(6, _translate("EnterDataDialog", "63"))
        self.lbl_purchase_rate_of_44_size.setText(_translate("EnterDataDialog", "Purchase rate of 44 size:"))
        self.lbl_cheque_no.setText(_translate("EnterDataDialog", "Cheque No.:"))
        self.date_edit_payment_paid_date.setDisplayFormat(_translate("EnterDataDialog", "dd/MM/yyyy"))
        self.lbl_selling_rate.setText(_translate("EnterDataDialog", "Selling Rate:"))
        self.lbl_payment_paid_amount.setText(_translate("EnterDataDialog", "Payment paid amount:"))
        self.lbl_gsm.setText(_translate("EnterDataDialog", "GSM:"))
        self.combo_box_gsm.setItemText(0, _translate("EnterDataDialog", "70"))
        self.combo_box_gsm.setItemText(1, _translate("EnterDataDialog", "100"))
        self.lbl_date.setText(_translate("EnterDataDialog", "Date:"))
        self.date_edit_date.setDisplayFormat(_translate("EnterDataDialog", "dd/MM/yyyy"))
        self.lbl_party_name.setText(_translate("EnterDataDialog", "Party Name:"))

